# Exploring the Data
by: Alissa Stover, Ying Hua, Sophia Skowronski

This Jupyter notebook walks through some data exploration steps for data from a Kaggle competition. 
The data and the complete data dictionary are here: https://www.kaggle.com/c/ashrae-energy-prediction/data

## Import packages

In [1]:
import pandas as pd

In [2]:
test_df = pd.read_pickle('test_df.pkl')
train_df = pd.read_pickle('train_df.pkl')

## Visually Inspect the Data

In [11]:
test_df.head()

<bound method NDFrame.head of           building_id  meter           timestamp  meter_reading  site_id  \
0                   0      0 2016-01-01 00:00:00       0.000000        0
1                   1      0 2016-01-01 00:00:00       0.000000        0
2                   2      0 2016-01-01 00:00:00       0.000000        0
3                   3      0 2016-01-01 00:00:00       0.000000        0
4                   4      0 2016-01-01 00:00:00       0.000000        0
5                   5      0 2016-01-01 00:00:00       0.000000        0
6                   6      0 2016-01-01 00:00:00       0.000000        0
7                   7      0 2016-01-01 00:00:00       0.000000        0
8                   8      0 2016-01-01 00:00:00       0.000000        0
9                   9      0 2016-01-01 00:00:00       0.000000        0
10                 10      0 2016-01-01 00:00:00       0.000000        0
11                 11      0 2016-01-01 00:00:00       0.000000        0
12                 12      0 2016-01-01 00:00:00       0.000000        0
13                 13      0 2016-01-01 00:00:00       0.000000        0
14                 14      0 2016-01-01 00:00:00       0.000000        0
15                 15      0 2016-01-01 00:00:00       0.000000        0
16                 16      0 2016-01-01 00:00:00       0.000000        0
17                 17      0 2016-01-01 00:00:00       0.000000        0
18                 18      0 2016-01-01 00:00:00       0.000000        0
19                 19      0 2016-01-01 00:00:00       0.000000        0
20                 20      0 2016-01-01 00:00:00       0.000000        0
21                 21      0 2016-01-01 00:00:00       0.000000        0
22                 22      0 2016-01-01 00:00:00       0.000000        0
23                 23      0 2016-01-01 00:00:00       0.000000        0
24                 24      0 2016-01-01 00:00:00       0.000000        0
25                 25      0 2016-01-01 00:00:00       0.000000        0
26                 26      0 2016-01-01 00:00:00       0.000000        0
27                 27      0 2016-01-01 00:00:00       0.000000        0
28                 28      0 2016-01-01 00:00:00       0.000000        0
29                 30      0 2016-01-01 00:00:00       0.000000        0
...               ...    ...                 ...            ...      ...
20216070         1427      0 2016-12-31 23:00:00     145.199997       15
20216071         1427      2 2016-12-31 23:00:00    3006.820068       15
20216072         1428      0 2016-12-31 23:00:00      38.724998       15
20216073         1429      0 2016-12-31 23:00:00      27.775000       15
20216074         1430      2 2016-12-31 23:00:00     318.567993       15
20216075         1431      0 2016-12-31 23:00:00      87.949997       15
20216076         1431      2 2016-12-31 23:00:00     426.339996       15
20216077         1432      0 2016-12-31 23:00:00     403.450012       15
20216078         1433      0 2016-12-31 23:00:00      41.349998       15
20216079         1433      2 2016-12-31 23:00:00    3173.879883       15
20216080         1434      0 2016-12-31 23:00:00      70.724998       15
20216081         1434      2 2016-12-31 23:00:00     259.072998       15
20216082         1435      0 2016-12-31 23:00:00       4.725000       15
20216083         1436      0 2016-12-31 23:00:00      11.600000       15
20216084         1436      2 2016-12-31 23:00:00    1274.660034       15
20216085         1437      0 2016-12-31 23:00:00     195.925003       15
20216086         1437      2 2016-12-31 23:00:00    1518.920044       15
20216087         1438      0 2016-12-31 23:00:00     100.675003       15
20216088         1438      2 2016-12-31 23:00:00     852.770020       15
20216089         1439      0 2016-12-31 23:00:00     167.399994       15
20216090         1440      0 2016-12-31 23:00:00     154.750000       15
20216091         1441      0 2016-12-31 23:00:00     242.925003       15
20216092         1442      0 2016-12-31 23:00:00      59.400002       15
20216093         1442      2 2016-12-31 23:00:00      55.624100       15
20216094         1443      0 2016-12-31 23:00:00      64.949997       15
20216095         1444      0 2016-12-31 23:00:00       8.750000       15
20216096         1445      0 2016-12-31 23:00:00       4.825000       15
20216097         1446      0 2016-12-31 23:00:00       0.000000       15
20216098         1447      0 2016-12-31 23:00:00     159.574997       15
20216099         1448      0 2016-12-31 23:00:00       2.850000       15

                            primary_use  square_feet  year_built  floor_count  \
0                             Education         7432      2008.0          NaN
1                             Education         2720      2004.0          NaN
2                             Education         5376      1991.0          NaN
3                             Education        23685      2002.0          NaN
4                             Education       116607      1975.0          NaN
5                             Education         8000      2000.0          NaN
6                   Lodging/residential        27926      1981.0          NaN
7                             Education       121074      1989.0          NaN
8                             Education        60809      2003.0          NaN
9                                Office        27000      2010.0          NaN
10        Entertainment/public assembly       370773      1991.0          NaN
11                            Education        49073      1968.0          NaN
12                  Lodging/residential        37100      1999.0          NaN
13                            Education        99380      2000.0          NaN
14                            Education        86250      2013.0          NaN
15                               Office        83957      1974.0          NaN
16                            Education        54644      1996.0          NaN
17                               Office        15250      1980.0          NaN
18                            Education       111891      1996.0          NaN
19                               Office        18717      2004.0          NaN
20                            Education       110272      1977.0          NaN
21                               Office         7043      1990.0          NaN
22                            Education         3569      1996.0          NaN
23                            Education       130885      1985.0          NaN
24                            Education       105545      2001.0          NaN
25                               Office       103286      1969.0          NaN
26                               Office        26953      2005.0          NaN
27                  Lodging/residential        59200      1999.0          NaN
28                               Office        52957      2016.0          NaN
29                            Education        93897      1999.0          NaN
...                                 ...          ...         ...          ...
20216070                      Education       180625      1933.0          NaN
20216071                      Education       180625      1933.0          NaN
20216072                      Education        28432      1933.0          NaN
20216073                      Education        40461      2002.0          NaN
20216074                         Office        53303      1981.0          NaN
20216075                Public services       111360      2000.0          NaN
20216076                Public services       111360      2000.0          NaN
20216077                      Education       160673      1968.0          NaN
20216078                      Education        28084      1913.0          NaN
20216079                      Education        28084      1913.0          NaN
20216080                      Education        33148      1967.0          NaN
20216081                      Education        33148      1967.0          NaN
20216082                      Education         9552      1961.0          NaN
20216083       Manufacturing/industrial        11302      1937.0          NaN
20216084       Manufacturing/industrial        11302      1937.0          NaN
20216085                      Education       111518      1968.0          NaN
20216086                      Education       111518      1968.0          NaN
20216087                      Education       108971      1990.0          NaN
20216088                      Education       108971      1990.0          NaN
20216089                      Education        56497      1957.0          NaN
20216090            Lodging/residential       150294      1987.0          NaN
20216091                      Education        30143      1951.0          NaN
20216092                Public services        99541      1993.0          NaN
20216093                Public services        99541      1993.0          NaN
20216094                      Education        40311      1913.0          NaN
20216095  Entertainment/public assembly        19619      1914.0          NaN
20216096                      Education         4298         NaN          NaN
20216097  Entertainment/public assembly        11265      1997.0          NaN
20216098            Lodging/residential        29775      2001.0          NaN
20216099                         Office        92271      2001.0          NaN

          air_temperature  cloud_coverage  dew_temperature  precip_depth_1_hr  \
0               25.000000             6.0        20.000000                NaN
1               25.000000             6.0        20.000000                NaN
2               25.000000             6.0        20.000000                NaN
3               25.000000             6.0        20.000000                NaN
4               25.000000             6.0        20.000000                NaN
5               25.000000             6.0        20.000000                NaN
6               25.000000             6.0        20.000000                NaN
7               25.000000             6.0        20.000000                NaN
8               25.000000             6.0        20.000000                NaN
9               25.000000             6.0        20.000000                NaN
10              25.000000             6.0        20.000000                NaN
11              25.000000             6.0        20.000000                NaN
12              25.000000             6.0        20.000000                NaN
13              25.000000             6.0        20.000000                NaN
14              25.000000             6.0        20.000000                NaN
15              25.000000             6.0        20.000000                NaN
16              25.000000             6.0        20.000000                NaN
17              25.000000             6.0        20.000000                NaN
18              25.000000             6.0        20.000000                NaN
19              25.000000             6.0        20.000000                NaN
20              25.000000             6.0        20.000000                NaN
21              25.000000             6.0        20.000000                NaN
22              25.000000             6.0        20.000000                NaN
23              25.000000             6.0        20.000000                NaN
24              25.000000             6.0        20.000000                NaN
25              25.000000             6.0        20.000000                NaN
26              25.000000             6.0        20.000000                NaN
27              25.000000             6.0        20.000000                NaN
28              25.000000             6.0        20.000000                NaN
29              25.000000             6.0        20.000000                NaN
...                   ...             ...              ...                ...
20216070         1.700195             NaN        -5.601562               -1.0
20216071         1.700195             NaN        -5.601562               -1.0
20216072         1.700195             NaN        -5.601562               -1.0
20216073         1.700195             NaN        -5.601562               -1.0
20216074         1.700195             NaN        -5.601562               -1.0
20216075         1.700195             NaN        -5.601562               -1.0
20216076         1.700195             NaN        -5.601562               -1.0
20216077         1.700195             NaN        -5.601562               -1.0
20216078         1.700195             NaN        -5.601562               -1.0
20216079         1.700195             NaN        -5.601562               -1.0
20216080         1.700195             NaN        -5.601562               -1.0
20216081         1.700195             NaN        -5.601562               -1.0
20216082         1.700195             NaN        -5.601562               -1.0
20216083         1.700195             NaN        -5.601562               -1.0
20216084         1.700195             NaN        -5.601562               -1.0
20216085         1.700195             NaN        -5.601562               -1.0
20216086         1.700195             NaN        -5.601562               -1.0
20216087         1.700195             NaN        -5.601562               -1.0
20216088         1.700195             NaN        -5.601562               -1.0
20216089         1.700195             NaN        -5.601562               -1.0
20216090         1.700195             NaN        -5.601562               -1.0
20216091         1.700195             NaN        -5.601562               -1.0
20216092         1.700195             NaN        -5.601562               -1.0
20216093         1.700195             NaN        -5.601562               -1.0
20216094         1.700195             NaN        -5.601562               -1.0
20216095         1.700195             NaN        -5.601562               -1.0
20216096         1.700195             NaN        -5.601562               -1.0
20216097         1.700195             NaN        -5.601562               -1.0
20216098         1.700195             NaN        -5.601562               -1.0
20216099         1.700195             NaN        -5.601562               -1.0

          sea_level_pressure  wind_direction  wind_speed
0                     1019.5             0.0    0.000000
1                     1019.5             0.0    0.000000
2                     1019.5             0.0    0.000000
3                     1019.5             0.0    0.000000
4                     1019.5             0.0    0.000000
5                     1019.5             0.0    0.000000
6                     1019.5             0.0    0.000000
7                     1019.5             0.0    0.000000
8                     1019.5             0.0    0.000000
9                     1019.5             0.0    0.000000
10                    1019.5             0.0    0.000000
11                    1019.5             0.0    0.000000
12                    1019.5             0.0    0.000000
13                    1019.5             0.0    0.000000
14                    1019.5             0.0    0.000000
15                    1019.5             0.0    0.000000
16                    1019.5             0.0    0.000000
17                    1019.5             0.0    0.000000
18                    1019.5             0.0    0.000000
19                    1019.5             0.0    0.000000
20                    1019.5             0.0    0.000000
21                    1019.5             0.0    0.000000
22                    1019.5             0.0    0.000000
23                    1019.5             0.0    0.000000
24                    1019.5             0.0    0.000000
25                    1019.5             0.0    0.000000
26                    1019.5             0.0    0.000000
27                    1019.5             0.0    0.000000
28                    1019.5             0.0    0.000000
29                    1019.5             0.0    0.000000
...                      ...             ...         ...
20216070              1008.5           180.0    8.796875
20216071              1008.5           180.0    8.796875
20216072              1008.5           180.0    8.796875
20216073              1008.5           180.0    8.796875
20216074              1008.5           180.0    8.796875
20216075              1008.5           180.0    8.796875
20216076              1008.5           180.0    8.796875
20216077              1008.5           180.0    8.796875
20216078              1008.5           180.0    8.796875
20216079              1008.5           180.0    8.796875
20216080              1008.5           180.0    8.796875
20216081              1008.5           180.0    8.796875
20216082              1008.5           180.0    8.796875
20216083              1008.5           180.0    8.796875
20216084              1008.5           180.0    8.796875
20216085              1008.5           180.0    8.796875
20216086              1008.5           180.0    8.796875
20216087              1008.5           180.0    8.796875
20216088              1008.5           180.0    8.796875
20216089              1008.5           180.0    8.796875
20216090              1008.5           180.0    8.796875
20216091              1008.5           180.0    8.796875
20216092              1008.5           180.0    8.796875
20216093              1008.5           180.0    8.796875
20216094              1008.5           180.0    8.796875
20216095              1008.5           180.0    8.796875
20216096              1008.5           180.0    8.796875
20216097              1008.5           180.0    8.796875
20216098              1008.5           180.0    8.796875
20216099              1008.5           180.0    8.796875

[20216100 rows x 16 columns]>

In [12]:
train_df.head()

<bound method NDFrame.head of             row_id  building_id  meter           timestamp  site_id  \
0                0            0      0 2017-01-01 00:00:00        0
1                1            1      0 2017-01-01 00:00:00        0
2                2            2      0 2017-01-01 00:00:00        0
3                3            3      0 2017-01-01 00:00:00        0
4                4            4      0 2017-01-01 00:00:00        0
5                5            5      0 2017-01-01 00:00:00        0
6                6            6      0 2017-01-01 00:00:00        0
7                7            7      0 2017-01-01 00:00:00        0
8                8            7      1 2017-01-01 00:00:00        0
9                9            8      0 2017-01-01 00:00:00        0
10              10            9      0 2017-01-01 00:00:00        0
11              11            9      1 2017-01-01 00:00:00        0
12              12           10      0 2017-01-01 00:00:00        0
13              13           11      0 2017-01-01 00:00:00        0
14              14           12      0 2017-01-01 00:00:00        0
15              15           13      0 2017-01-01 00:00:00        0
16              16           13      1 2017-01-01 00:00:00        0
17              17           14      0 2017-01-01 00:00:00        0
18              18           14      1 2017-01-01 00:00:00        0
19              19           15      0 2017-01-01 00:00:00        0
20              20           15      1 2017-01-01 00:00:00        0
21              21           16      0 2017-01-01 00:00:00        0
22              22           17      0 2017-01-01 00:00:00        0
23              23           18      0 2017-01-01 00:00:00        0
24              24           19      0 2017-01-01 00:00:00        0
25              25           20      0 2017-01-01 00:00:00        0
26              26           21      0 2017-01-01 00:00:00        0
27              27           22      0 2017-01-01 00:00:00        0
28              28           23      0 2017-01-01 00:00:00        0
29              29           24      0 2017-01-01 00:00:00        0
...            ...          ...    ...                 ...      ...
41697570  41697570         1427      2 2018-05-09 07:00:00       15
41697571  41697571         1428      0 2018-05-09 07:00:00       15
41697572  41697572         1429      0 2018-05-09 07:00:00       15
41697573  41697573         1430      0 2018-05-09 07:00:00       15
41697574  41697574         1430      2 2018-05-09 07:00:00       15
41697575  41697575         1431      0 2018-05-09 07:00:00       15
41697576  41697576         1431      2 2018-05-09 07:00:00       15
41697577  41697577         1432      0 2018-05-09 07:00:00       15
41697578  41697578         1433      0 2018-05-09 07:00:00       15
41697579  41697579         1433      2 2018-05-09 07:00:00       15
41697580  41697580         1434      0 2018-05-09 07:00:00       15
41697581  41697581         1434      2 2018-05-09 07:00:00       15
41697582  41697582         1435      0 2018-05-09 07:00:00       15
41697583  41697583         1436      0 2018-05-09 07:00:00       15
41697584  41697584         1436      2 2018-05-09 07:00:00       15
41697585  41697585         1437      0 2018-05-09 07:00:00       15
41697586  41697586         1437      2 2018-05-09 07:00:00       15
41697587  41697587         1438      0 2018-05-09 07:00:00       15
41697588  41697588         1438      2 2018-05-09 07:00:00       15
41697589  41697589         1439      0 2018-05-09 07:00:00       15
41697590  41697590         1440      0 2018-05-09 07:00:00       15
41697591  41697591         1441      0 2018-05-09 07:00:00       15
41697592  41697592         1442      0 2018-05-09 07:00:00       15
41697593  41697593         1442      2 2018-05-09 07:00:00       15
41697594  41697594         1443      0 2018-05-09 07:00:00       15
41697595  41697595         1444      0 2018-05-09 07:00:00       15
41697596  41697596         1445      0 2018-05-09 07:00:00       15
41697597  41697597         1446      0 2018-05-09 07:00:00       15
41697598  41697598         1447      0 2018-05-09 07:00:00       15
41697599  41697599         1448      0 2018-05-09 07:00:00       15

                            primary_use  square_feet  year_built  floor_count  \
0                             Education         7432      2008.0          NaN
1                             Education         2720      2004.0          NaN
2                             Education         5376      1991.0          NaN
3                             Education        23685      2002.0          NaN
4                             Education       116607      1975.0          NaN
5                             Education         8000      2000.0          NaN
6                   Lodging/residential        27926      1981.0          NaN
7                             Education       121074      1989.0          NaN
8                             Education       121074      1989.0          NaN
9                             Education        60809      2003.0          NaN
10                               Office        27000      2010.0          NaN
11                               Office        27000      2010.0          NaN
12        Entertainment/public assembly       370773      1991.0          NaN
13                            Education        49073      1968.0          NaN
14                  Lodging/residential        37100      1999.0          NaN
15                            Education        99380      2000.0          NaN
16                            Education        99380      2000.0          NaN
17                            Education        86250      2013.0          NaN
18                            Education        86250      2013.0          NaN
19                               Office        83957      1974.0          NaN
20                               Office        83957      1974.0          NaN
21                            Education        54644      1996.0          NaN
22                               Office        15250      1980.0          NaN
23                            Education       111891      1996.0          NaN
24                               Office        18717      2004.0          NaN
25                            Education       110272      1977.0          NaN
26                               Office         7043      1990.0          NaN
27                            Education         3569      1996.0          NaN
28                            Education       130885      1985.0          NaN
29                            Education       105545      2001.0          NaN
...                                 ...          ...         ...          ...
41697570                      Education       180625      1933.0          NaN
41697571                      Education        28432      1933.0          NaN
41697572                      Education        40461      2002.0          NaN
41697573                         Office        53303      1981.0          NaN
41697574                         Office        53303      1981.0          NaN
41697575                Public services       111360      2000.0          NaN
41697576                Public services       111360      2000.0          NaN
41697577                      Education       160673      1968.0          NaN
41697578                      Education        28084      1913.0          NaN
41697579                      Education        28084      1913.0          NaN
41697580                      Education        33148      1967.0          NaN
41697581                      Education        33148      1967.0          NaN
41697582                      Education         9552      1961.0          NaN
41697583       Manufacturing/industrial        11302      1937.0          NaN
41697584       Manufacturing/industrial        11302      1937.0          NaN
41697585                      Education       111518      1968.0          NaN
41697586                      Education       111518      1968.0          NaN
41697587                      Education       108971      1990.0          NaN
41697588                      Education       108971      1990.0          NaN
41697589                      Education        56497      1957.0          NaN
41697590            Lodging/residential       150294      1987.0          NaN
41697591                      Education        30143      1951.0          NaN
41697592                Public services        99541      1993.0          NaN
41697593                Public services        99541      1993.0          NaN
41697594                      Education        40311      1913.0          NaN
41697595  Entertainment/public assembly        19619      1914.0          NaN
41697596                      Education         4298         NaN          NaN
41697597  Entertainment/public assembly        11265      1997.0          NaN
41697598            Lodging/residential        29775      2001.0          NaN
41697599                         Office        92271      2001.0          NaN

          air_temperature  cloud_coverage  dew_temperature  precip_depth_1_hr  \
0               17.796875             4.0        11.703125                NaN
1               17.796875             4.0        11.703125                NaN
2               17.796875             4.0        11.703125                NaN
3               17.796875             4.0        11.703125                NaN
4               17.796875             4.0        11.703125                NaN
5               17.796875             4.0        11.703125                NaN
6               17.796875             4.0        11.703125                NaN
7               17.796875             4.0        11.703125                NaN
8               17.796875             4.0        11.703125                NaN
9               17.796875             4.0        11.703125                NaN
10              17.796875             4.0        11.703125                NaN
11              17.796875             4.0        11.703125                NaN
12              17.796875             4.0        11.703125                NaN
13              17.796875             4.0        11.703125                NaN
14              17.796875             4.0        11.703125                NaN
15              17.796875             4.0        11.703125                NaN
16              17.796875             4.0        11.703125                NaN
17              17.796875             4.0        11.703125                NaN
18              17.796875             4.0        11.703125                NaN
19              17.796875             4.0        11.703125                NaN
20              17.796875             4.0        11.703125                NaN
21              17.796875             4.0        11.703125                NaN
22              17.796875             4.0        11.703125                NaN
23              17.796875             4.0        11.703125                NaN
24              17.796875             4.0        11.703125                NaN
25              17.796875             4.0        11.703125                NaN
26              17.796875             4.0        11.703125                NaN
27              17.796875             4.0        11.703125                NaN
28              17.796875             4.0        11.703125                NaN
29              17.796875             4.0        11.703125                NaN
...                   ...             ...              ...                ...
41697570              NaN             NaN              NaN                NaN
41697571              NaN             NaN              NaN                NaN
41697572              NaN             NaN              NaN                NaN
41697573              NaN             NaN              NaN                NaN
41697574              NaN             NaN              NaN                NaN
41697575              NaN             NaN              NaN                NaN
41697576              NaN             NaN              NaN                NaN
41697577              NaN             NaN              NaN                NaN
41697578              NaN             NaN              NaN                NaN
41697579              NaN             NaN              NaN                NaN
41697580              NaN             NaN              NaN                NaN
41697581              NaN             NaN              NaN                NaN
41697582              NaN             NaN              NaN                NaN
41697583              NaN             NaN              NaN                NaN
41697584              NaN             NaN              NaN                NaN
41697585              NaN             NaN              NaN                NaN
41697586              NaN             NaN              NaN                NaN
41697587              NaN             NaN              NaN                NaN
41697588              NaN             NaN              NaN                NaN
41697589              NaN             NaN              NaN                NaN
41697590              NaN             NaN              NaN                NaN
41697591              NaN             NaN              NaN                NaN
41697592              NaN             NaN              NaN                NaN
41697593              NaN             NaN              NaN                NaN
41697594              NaN             NaN              NaN                NaN
41697595              NaN             NaN              NaN                NaN
41697596              NaN             NaN              NaN                NaN
41697597              NaN             NaN              NaN                NaN
41697598              NaN             NaN              NaN                NaN
41697599              NaN             NaN              NaN                NaN

          sea_level_pressure  wind_direction  wind_speed
0                     1021.5           100.0    3.599609
1                     1021.5           100.0    3.599609
2                     1021.5           100.0    3.599609
3                     1021.5           100.0    3.599609
4                     1021.5           100.0    3.599609
5                     1021.5           100.0    3.599609
6                     1021.5           100.0    3.599609
7                     1021.5           100.0    3.599609
8                     1021.5           100.0    3.599609
9                     1021.5           100.0    3.599609
10                    1021.5           100.0    3.599609
11                    1021.5           100.0    3.599609
12                    1021.5           100.0    3.599609
13                    1021.5           100.0    3.599609
14                    1021.5           100.0    3.599609
15                    1021.5           100.0    3.599609
16                    1021.5           100.0    3.599609
17                    1021.5           100.0    3.599609
18                    1021.5           100.0    3.599609
19                    1021.5           100.0    3.599609
20                    1021.5           100.0    3.599609
21                    1021.5           100.0    3.599609
22                    1021.5           100.0    3.599609
23                    1021.5           100.0    3.599609
24                    1021.5           100.0    3.599609
25                    1021.5           100.0    3.599609
26                    1021.5           100.0    3.599609
27                    1021.5           100.0    3.599609
28                    1021.5           100.0    3.599609
29                    1021.5           100.0    3.599609
...                      ...             ...         ...
41697570                 NaN             NaN         NaN
41697571                 NaN             NaN         NaN
41697572                 NaN             NaN         NaN
41697573                 NaN             NaN         NaN
41697574                 NaN             NaN         NaN
41697575                 NaN             NaN         NaN
41697576                 NaN             NaN         NaN
41697577                 NaN             NaN         NaN
41697578                 NaN             NaN         NaN
41697579                 NaN             NaN         NaN
41697580                 NaN             NaN         NaN
41697581                 NaN             NaN         NaN
41697582                 NaN             NaN         NaN
41697583                 NaN             NaN         NaN
41697584                 NaN             NaN         NaN
41697585                 NaN             NaN         NaN
41697586                 NaN             NaN         NaN
41697587                 NaN             NaN         NaN
41697588                 NaN             NaN         NaN
41697589                 NaN             NaN         NaN
41697590                 NaN             NaN         NaN
41697591                 NaN             NaN         NaN
41697592                 NaN             NaN         NaN
41697593                 NaN             NaN         NaN
41697594                 NaN             NaN         NaN
41697595                 NaN             NaN         NaN
41697596                 NaN             NaN         NaN
41697597                 NaN             NaN         NaN
41697598                 NaN             NaN         NaN
41697599                 NaN             NaN         NaN

[41697600 rows x 16 columns]>

## Data Dictionary 

Here are our starting variables for the training dataset:

1. **building_id** - Foreign key for the building metadata.
2. **meter** - The meter id code. Read as {0: electricity, 1: chilledwater, 2: steam, 3: hotwater}. Not every building has all meter types.
3. **timestamp** - When the measurement was taken
4. **meter_reading** - The target variable. Energy consumption in kWh (or equivalent). Note that this is real data with measurement error, which we expect will impose a baseline level of modeling error.
5. **site_id** - Foreign key for the weather files.
6. **primary_use** - Indicator of the primary category of activities for the building based on EnergyStar property type definitions
7. **square_feet** - Gross floor area of the building
8. **year_built** - Year building was opened
9. **floor_count** - Number of floors of the building
10. **air_temperature** - Degrees Celsius
11. **cloud_coverage** - Portion of the sky covered in clouds, in oktas
12. **dew_temperature** - Degrees Celsius
13. **precip_depth_1_hr** - Millimeters
14. **sea_level_pressure** - Millibar/hectopascals
15. **wind_direction** - Compass direction (0-360)
16. **wind_speed** - Meters per second

## Generate Univariate Statistics of Train Dataset

Create some descriptive statistics of the quantitative variables.

In [13]:
train_df.describe()

,building_id,meter,meter_reading,site_id,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
count,2.021610e+07,2.021610e+07,2.021610e+07,2.021610e+07,2.021610e+07,8088455.0,3506933.0,2.011944e+07,11390735.0,2.011596e+07,16467077.0,18984431.0,18767052.0,2.007242e+07
mean,7.992780e+02,6.624412e-01,1.988706e+03,7.992232e+00,1.077830e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.269133e+02,9.309921e-01,1.532159e+05,5.099060e+00,1.171424e+05,NaN,0.0,0.000000e+00,0.0,0.000000e+00,NaN,NaN,NaN,0.000000e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.830000e+02,1900.0,1.0,-2.890625e+01,0.0,-3.500000e+01,-1.0,968.0,0.0,0.000000e+00
25%,3.930000e+02,0.000000e+00,1.830000e+01,3.000000e+00,3.252700e+04,1951.0,1.0,8.601562e+00,0.0,0.000000e+00,0.0,1011.5,70.0,2.099609e+00
50%,8.950000e+02,0.000000e+00,7.877500e+01,9.000000e+00,7.270900e+04,1969.0,3.0,1.670312e+01,0.0,8.898438e+00,0.0,1016.0,180.0,3.099609e+00
75%,1.179000e+03,1.000000e+00,2.679840e+02,1.300000e+01,1.391130e+05,1993.0,6.0,2.409375e+01,4.0,1.609375e+01,0.0,1020.5,280.0,4.601562e+00
max,1.448000e+03,3.000000e+00,2.190470e+07,1.500000e+01,8.750000e+05,2017.0,26.0,4.718750e+01,9.0,2.609375e+01,343.0,1046.0,360.0,1.900000e+01

In the above, we can see a lot of missing data (the *count* for different variables is not the same number and we have a lot of NaN for *mean* and *standard deviation*).

Here are some observations about our columns:

* **building_id**
    * Looks reasonable -- not seeing any obvious data quality issues from these stats alone
* **meter**
    * Looks reasonable -- not seeing any obvious data quality issues from these stats alone
* **meter_reading**
    * Looks reasonable -- not seeing any obvious data quality issues from these stats alone
* **site_id**
    * Looks reasonable -- not seeing any obvious data quality issues from these stats alone
* **square_feet**
    * Looks reasonable -- not seeing any obvious data quality issues from these stats alone
* **year_built**
    * A lot of missing data here. There is also quite a range -- at least 1900-2017. I assume that the data are missing within each building so that we can't just fill in missing values but will instead have to interpolate somehow. 
* **floor_count**
    * Even more missing data here! Goes from 1-26 floors. Perhaps we can interpolate the missing data based on square footage -- e.g., if a building has the same square footage as another building that is recorded as having 8 floors, it would be a good guess that the one with missing data also has around 8 floors. However, in that case we would want to quantify the relationship between number of floors and square footage in the data that are not missing. And if they are highly correlated, maybe we should just use the square footage information since the quality is better. 
* **air_temperature**
    * There is some missing data here. Maybe we could interpolate for a building based on the time of day and the month (e.g., in June at 8am at this building it is usually 20 degrees celsius so let's guess it is that). 
    * Also to note -- this is in celsius.
* **cloud_coverage**
    * Also is missing a lot of data. I don't understand this variable very well so I will have to research it a bit to figure out if we should include it or try to interpolate and use it.
* **dew_temperature**
    * Some missing data but not too bad. Might want to use a similar interpolation strategy as for air temperature (based on the time of day and the month). Maybe we can also see if this and cloud coverage have a relationship and interpolate cloud coverage based on this. But if they are very related, maybe we should just pick one (dew temperature probably since the data quality seems higher).
* **precip_depth_1_hr**
    * First thing to note -- what does a value of (-1) mean? Should we take a moving average instead perhaps to rectify that?
    * Also has a lot of missing data. This seems like it might be important so we should think about this more.
* **sea_level_pressure**
    * Missing a lot of data. I don't know much about this variable so need to do more background research if I am going to use it. 
* **wind_direction**
    * Also missing a lot of data. Not sure if this variable is important so should read more background on it. 
* **wind_speed**
    * Not missing a lot of data! And the stats look reasonable. Might be a good one to use.

Look at the one categorical variable

In [14]:
train_df.primary_use.describe()

count      20216100
unique           16
top       Education
freq        8165504
Name: primary_use, dtype: object

In [15]:
uses = train_df.primary_use.unique()
for i in range(0, len(uses)):
    print(uses[i])

Education
Lodging/residential
Office
Entertainment/public assembly
Other
Retail
Parking
Public services
Warehouse/storage
Food sales and service
Religious worship
Healthcare
Utility
Technology/science
Manufacturing/industrial
Services

**primary_use** does not have any missing data and has 16 unique categories.

Let's look at our time/date variable

In [16]:
train_df.timestamp.describe()

count                20216100
unique                   8784
top       2016-12-27 22:00:00
freq                     2370
first     2016-01-01 00:00:00
last      2016-12-31 23:00:00
Name: timestamp, dtype: object

We are not missing any data/time data. The data appear to be in a consistent format and range from Jan 1st (midnight) - Dec 31st (midnight) 2016.
2016 is a leap year so there is data for 366 days. 
It appears that the time is not in local time, so we should probably transform it based on the building location if we can find that inforamtion. We might also want to mark which days are work days & holidays based on the building location.

## Select variables to focus on in the training dataset

Not all of these variables are going to be central to our analysis. 

Our target variable is **meter_reading**

These are some important identification variables related to the buildings:

* **site_id**
* **building_id**

For **meter_reading**, we would expect some influence to come from the type of meter, recorded in the **meter** variable. 

The **timestamp** variable is very important in general -- this is our unit of analysis. 

These variables are related to the building's characteristics:

* **square_feet**
* **year_built**
* **floor_count** 
* **primary_use** -- this is a categorical variable

Since there are issues with the floor count variable, maybe we can just use the others and avoid it for now. Otherwise, maybe we can somehow use it to mark which buildings are skyscrapers (and interpolate the missing ones with square feet & primary use) -- I think they tend to be really inefficient so perhaps having a binary variable to track that would be helpful. 

These are weather variables, in the order of how important/useful I assume they are based on what I know now (which is little): 

* **air_temperature**
* **dew_temperature**
* **wind_speed**
* **precip_depth_1_hr**
* **wind_direction**
* **cloud_coverage** 
* **sea_level_pressure**

## Select variables from the training dataset for cleaning 

These are the variables that don't have missing data but we should check them for outliers and values that do not seem reasonable. We should also consider performing some transformations on them: 

* **meter_reading** -> this is our target variable; we need to be 100& sure this variable is clean; there are some concerns that some 0 values are truly missing data 
* **site_id** -> most likely OK
* **building_id** -> used successfully for the merge; most likely OK
* **meter** -> most likely OK
* **square_feet** -> most likely OK
* **primary_use** -> most likely OK
* **timestamp** -> most likely OK; as noted above, might want to transform to local time & mark what days are work days or not and which days are holidays. 

These variables have missing data and are important so we should figure out how to clean them up. Also of course need to check for outliers and that values are reasonable:

* **year_built**
* **air_temperature**
* **dew_temperature**
* **wind_speed**
* **precip_depth_1_hr**
* **wind_direction**

These variables seems less important and less worth cleaning for use:

* **floor_count**
* **cloud_coverage** 
* **sea_level_pressure**